# .github/workflows/release.yml

name: Build and Release

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        targets: x86_64-pc-windows-msvc
        components: rustfmt, clippy

    - name: Run cargo check
      run: cargo check

    - name: Run cargo test
      run: cargo test

    - name: Run cargo build (release)
      run: cargo build --release --locked

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FlurionsPythonBindings-${{ github.run_id }}  # Unique name per run
        path: |
          target/release/FlurionsPythonBindings.exe
          Cargo.lock
        retention-days: 90  # Keep artifacts for 90 days
